#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
#@ load("@ytt:yaml", "yaml")
#@ load("/helpers.star", "is_package_additional")

#@ if is_package_additional("developer-portal"):

#@ def compute_package_values():
#@   values = struct.decode(data.values.developer_portal)
#@   return struct.encode(values)
#@ end

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: developer-portal
  namespace: #@ data.values.platform.namespace
  annotations:
    kapp.k14s.io/change-group: developer-portal
    kapp.k14s.io/change-rule.cert-manager: upsert after upserting cert-manager
    kapp.k14s.io/change-rule.contour: upsert after upserting contour
    kapp.k14s.io/change-rule.serviceaccount: delete before deleting serviceaccount
spec:
  serviceAccountName: kadras-install-sa
  packageRef:
    refName: developer-portal.packages.kadras.io
    versionSelection:
      constraints: 0.4.1
  values:
    - secretRef:
        name: developer-portal-values
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-portal-values
  namespace: #@ data.values.platform.namespace
stringData:
  values.yaml: #@ yaml.encode(compute_package_values())

#@ end