#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
#@ load("@ytt:yaml", "yaml")
#@ load("/helpers.star", "get_issuer_name", "is_any_profile_enabled", "is_package_enabled", "profiles")

#@ if is_package_enabled("knative-serving") and is_any_profile_enabled([profiles.standalone, profiles.run]):

#@ def compute_package_values():
#@   values = struct.decode(data.values.knative.serving)
#@
#@   #! Compute values for CA Certificates
#@   if data.values.platform.ca_cert_data and (not hasattr(data.values.knative.serving, "ca_cert_data") or not data.values.knative.serving.ca_cert_data):
#@     values["ca_cert_data"] = data.values.platform.ca_cert_data
#@   end
#@
#@   #! Compute values for Ingress Domain Name
#@   if data.values.platform.ingress.domain and (not hasattr(data.values.knative.serving, "domain_name") or not data.values.knative.serving.domain_name):
#@     values["domain_name"] = data.values.platform.ingress.domain
#@   end
#@
#@   #! Compute values for Ingress Issuer
#@   if data.values.platform.ingress.issuer and (not hasattr(data.values.knative.serving, "ingress_issuer") or not data.values.knative.serving.ingress_issuer):
#@     values["ingress_issuer"] = get_issuer_name(data.values.platform.ingress.issuer)
#@   end
#@
#@   return struct.encode(values)
#@ end

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: knative-serving
  namespace: #@ data.values.platform.namespace
  annotations:
    kapp.k14s.io/change-group: knative-serving
    kapp.k14s.io/change-rule.cert-manager: upsert after upserting cert-manager
    kapp.k14s.io/change-rule.contour: upsert after upserting contour
    kapp.k14s.io/change-rule.serviceaccount: delete before deleting serviceaccount
spec:
  serviceAccountName: kadras-install-sa
  packageRef:
    refName: knative-serving.packages.kadras.io
    versionSelection:
      constraints: 1.19.5
  values:
    - secretRef:
        name: knative-serving-values
---
apiVersion: v1
kind: Secret
metadata:
  name: knative-serving-values
  namespace: #@ data.values.platform.namespace
stringData:
  values.yaml: #@ yaml.encode(compute_package_values())

#@ end