#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
#@ load("@ytt:yaml", "yaml")
#@ load("/helpers.star", "is_package_additional")

#@ if is_package_additional("weaviate"):

#@ def compute_package_values():
#@   values = struct.decode(data.values.weaviate)
#@   return struct.encode(values)
#@ end

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: weaviate
  namespace: #@ data.values.platform.namespace
  annotations:
    kapp.k14s.io/change-group: weaviate
    kapp.k14s.io/change-rule.secretgen-controller: upsert after upserting secretgen-controller
    kapp.k14s.io/change-rule.serviceaccount: delete before deleting serviceaccount
spec:
  serviceAccountName: kadras-install-sa
  packageRef:
    refName: weaviate.packages.kadras.io
    versionSelection:
      constraints: 1.25.4
  values:
    - secretRef:
        name: weaviate-values
---
apiVersion: v1
kind: Secret
metadata:
  name: weaviate-values
  namespace: #@ data.values.platform.namespace
stringData:
  values.yaml: #@ yaml.encode(compute_package_values())

#@ end