apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: engineering-platform.packages.kadras.io.0.0.0
spec:
  licenses:
  - Apache 2.0
  refName: engineering-platform.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/kadras-engineering-platform/releases
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: {}
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: engineering-platform.packages.kadras.io
spec:
  categories:
  - internal developer platform
  - application platform
  displayName: engineering-platform
  longDescription: A cloud native platform aimed at supporting application developers
    with paved paths to production on Kubernetes and shipped as a Carvel package.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: Cloud native engineering platform on Kubernetes.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/kadras-engineering-platform
    for community support.

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: engineering-platform
spec:
  packageRef:
    refName: engineering-platform.packages.kadras.io
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kadras-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
